apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-network
  namespace: default
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: target-app
    ports:
    - port: 5432
      protocol: TCP
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: target-app-network
  namespace: default
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 100.26.132.199/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 100.57.32.83/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 13.216.77.144/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 13.223.23.68/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 18.204.239.121/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 32.194.128.236/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 52.73.10.94/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 54.147.121.219/32
  - ports:
    - port: 5432
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: postgres
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: traffic-generator
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: target-app
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: traffic-generator-network
  namespace: default
spec:
  egress:
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: target-app
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  podSelector:
    matchLabels:
      run: traffic-generator
  policyTypes:
  - Ingress
  - Egress
